Include a CUDA test in 'make check'

diff --git a/src/eps/tests/makefile b/src/eps/tests/makefile
--- a/src/eps/tests/makefile
+++ b/src/eps/tests/makefile
@@ -99,3 +99,24 @@ testtest10: test10.PETSc
 	else fail=1; fi; \
 	exit $$fail
 
+testtest10_cuda: test10.PETSc
+	@fail=0; if [ "${PETSC_WITH_BATCH}" != "" ]; then \
+	  echo "Running with batch filesystem; to test run src/eps/tests/test10" ; \
+	  echo "with your systems batch system"; \
+	elif [ "${MPIEXEC}" = "/bin/false" ]; then \
+	  echo "*mpiexec not found*. Please run src/eps/tests/test10 manually"; \
+	elif [ -f test10 ]; then \
+	  test=test10_1; check=test10_1_ks; \
+	  options="-eps_nev 4 -eps_ncv 14 -m 11 -eps_largest_magnitude -mat_type aijcusparse"; \
+	  ${MPIEXEC} -n 1 ./test10 $$options > $${test}.tmp 2>&1; \
+	  if (${DIFF} output/$${check}.out $${test}.tmp > /dev/null 2>&1) then \
+	    echo "C/C++ example src/eps/tests/test10 run successfully with CUDA"; \
+	  else \
+	    echo "Possible error running C/C++ src/eps/tests/test10 with CUDA"; \
+	    cat $${test}.tmp; fail=1; \
+	  fi; \
+	  ${RM} $${test}.tmp; \
+	  ${MAKE} SLEPC_DIR=${SLEPC_DIR} PETSC_ARCH=${PETSC_ARCH} PETSC_DIR=${PETSC_DIR} test10.rm; \
+	else fail=1; fi; \
+	exit $$fail
+
